### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by JDubbTX** [tom-writes-code/rpgle-repl#13]
I installed to my organization's IBM i by
1) cloning this repository to an IFS directory
2) Modifying iproj.json to point to an existing library
3) In an SSH session, change to the cloned directory and running makei build

When I try to compile something with the tool, the spool file listing has an issue opening an include member.  Image of the spool listing is attached.

I do have the target library where the objects were installed in the library list.

![image](https://user-images.githubusercontent.com/56802156/164308500-fcacd8c8-7e78-49dc-9698-4cbf2272260a.png)

**Comment by JDubbTX** [comment]
Looks like the install did not copy the include member into the target library.  Manually creating the qrpgleref source file and copying the qrpgleref source from IFS seems to have resolved this issue.

**Comment by martintosney** [comment]
Hi @JDubbTX, thanks for checking out the project!

I'd be interested in debugging why the reference source wasn't copied over, if you don't mind. With a fresh target library for the build, could you please run:

`makei refs`

That should give you an output like this:

```$ COLORBOB=true makei refs
makei: Reading from iproj.json
......objlib: REPLBOB
......curlib: REPLBOB
......tgtCcsid: *JOB
......IBMiEnvCmdList:
......includePathList:
......preUsrlibl:
......postUsrlibl:

Generating makefile for build variables at /tmp/tmp.a6k8XSq6W4

>> make -k BUILDVARSMKPATH=/tmp/tmp.a6k8XSq6W4 COLOR_TTY=true -f /QOpenSys/pkgs/lib/bob/Makefile refs
=== Creating source PF [QRPGLEREF.FILE]
CRTSRCPF FILE(REPLBOB/QRPGLEREF) RCDLEN(112) CCSID(37)
=== Creating ref member [REPL_HLPR.MBR]
CPYFRMSTMF FROMSTMF('/home/martint/code/rpgle-repl/rpgle/REPL_HLPR.RPGLEINC') TOMBR('/QSYS.LIB/REPLBOB.LIB/QRPGLEREF.FILE/REPL_HLPR.MBR') MBROPT(*REPLACE)
=== Creating ref member [REPL_PSEUT.MBR]
CPYFRMSTMF FROMSTMF('/home/martint/code/rpgle-repl/rpgle/REPL_PSEUT.RPGLEINC') TOMBR('/QSYS.LIB/REPLBOB.LIB/QRPGLEREF.FILE/REPL_PSEUT.MBR') MBROPT(*REPLACE)

Cleaning up...

Done.
```

If you don't see any errors in the console, could you take a look at the contents of `.logs/output.log` within your project directory and see if there any errors please? Thanks!

**Comment by JDubbTX** [comment]
I'm wondering if the version of BOB i have is incompatible. or didn't install correctly.  
We recently installed this version:  https://github.com/IBM/ibmi-bob
Output from makei refs:
![image](https://user-images.githubusercontent.com/56802156/164324025-1106b014-896a-4219-8dd7-c959e047e450.png)

**Comment by martintosney** [comment]
Ah, interesting. We have a slightly old version of Bob installed (2.2.7) and it looks like there have been some considerable changes to the project since then.

I'll get our version upgraded and then see if I need to update the build files as a result.

**Comment by martintosney** [comment]
Hey @JDubbTX, I made some updates yesterday to make this compatible with Bob v2.3.3. Hopefully it will work for you now!

**Comment by JDubbTX** [comment]
This is now working for me.  Thanks!
