### ISSUE TITLE
Cannot use a binding directory, or any other ctl-opt statements

### ISSUE THREAD

**Issue by JDubbTX** [tom-writes-code/rpgle-repl#14]
I tried having a ctl-opt statement on the first line of code to specify a binding directory to use for an exported sub procedure in a service program.

That doesn't seem to be viable when I look at the attached screenshot of the spool listing.  It would be very nice to have this ability in order to have snippets that demonstrate usage of existing service programs.

![image](https://user-images.githubusercontent.com/56802156/164310832-a600e0a1-d236-4273-b5fa-26cd8f42eac3.png)

**Comment by martintosney** [comment]
I could see this being useful. Our organisation don't use that many binding directories, so REPL's ability to bind service programs based off `/include`d copybooks has worked well enough for us.

**Comment by tom-writes-code** [comment]
This is something I initially looked at, but we didn't have enough use cases to justify it at the time.

Control specifications _seem_ like things that are generally fairly static within an organisation, so I'd like to put in a solution that allows a user to set a default control specification for all users, and also allows users to override that default with a snippet-specific specification whenever they want.

**Comment by tom-writes-code** [comment]
I've documented these use cases on the wiki here: https://github.com/tom-writes-code/rpgle-repl/wiki/How-to-use#setting-control-statements
