### ISSUE TITLE
Saved snippets save under group profile name

### ISSUE THREAD

**Issue by majkrebs** [tom-writes-code/rpgle-repl#16]
I saved a snippet, went to load it and it wasn't there. Figured out I could wipe out the profile to see all and discovered my saved snippets under my group profile. 

I would like to see them saved under my actual profile (the one shown when I go to the load screen).
Version: 76312E302E302D626574  61

**Comment by martintosney** [comment]
It looks like all the snippets code uses the SQL `CURRENT USER` register, whereas the value displayed for the user filter is equivalent to `SESSION USER`. That's an easy enough change.

It sounds like you have an interesting set up, though. Do you log in as that group user, and then somehow change your effective user after logging in?

**Comment by majkrebs** [comment]
We login as the "session user" but all our objects are owned by the group. That makes what little security we use easier. 
Thanks for sharing your creation with the community. 
Mike
 
 
  On Wed, Apr 20, 2022 at 6:36 PM, Martin ***@***.***> wrote:   


It looks like all the snippets code uses the SQL CURRENT USER register, whereas the value displayed for the user filter is equivalent to SESSION USER. That's an easy enough change.

It sounds like you have an interesting set up, though. Do you log in as that group user, and then somehow change your effective user after logging in?

**Comment by tom-writes-code** [comment]
Great enthusiasm GitHub, but I'll keep this open until I publish it into a save file.

**Comment by tom-writes-code** [comment]
The new save file in release v1.1.0-beta should resolve this.
