### ISSUE TITLE
REPLREFBLD in *LIBL type *FILE not found.

### ISSUE THREAD

**Issue by GilDew** [tom-writes-code/rpgle-repl#24]
I get this msg when compiling. REPLREFBLD doesn't seem to be included in the savf. What did I miss? I installed using the save file RPGLEREPL.FILE

**Comment by tom-writes-code** [comment]
This was a planned development that fizzled out and can be ignored.

I've updated the source files to remove mention of it, but I haven't published a new version yet.

Is this something that prevents compilation? I wonder if we've just had a more forgiving compiler setting.

**Comment by GilDew** [comment]
Yes it prevents compilations. 😊

**Comment by GilDew** [comment]
My apology. It doesn’t seem to prevent compilation! 😊

**Comment by tom-writes-code** [comment]
The new save file v1.1.0-beta should resolve this.

**Comment by GilDew** [comment]
Thanks!
