### ISSUE TITLE
Including reference sources with fixed format RPG does not compile

### ISSUE THREAD

**Issue by nickleefnz** [tom-writes-code/rpgle-repl#40]
We have a number of reference sources which contain fixed format. Currently, if we attempt to `/include` these in REPL then it fails to compile. It would be nice to be able to use these in REPL.

I've also been informed that reference sources in free format with comments after declarations also fails to compile.

E.g. `dcl-c someConstant 'blah'; // Some constant` in a reference source won't compile if we `/include` it

**Comment by tom-writes-code** [comment]
I looked into this, and them being fixed format was a bit of a red herring, it is just anything where we have a comment mid-line, we don't realise we should stop reading it.

I suspect there's a bigger and more interesting problem around `/* */` style comments, which I might not address quite yet.
