### ISSUE TITLE
Combine Tested function with Assert not working

### ISSUE THREAD

**Issue by JDubbTX** [tom-writes-code/rpgle-repl#55]
Love the new assert functionality.  When testing it out, I came across this, where test result is not printed.

Everything in this screenshot is working as it should:

![Screenshot 2024-07-02 090933](https://github.com/tom-writes-code/rpgle-repl/assets/56802156/234d66f5-69fe-41d0-add1-ad2d403d1021)

But if I nest the function I'm trying to test with 'Assert', the result is not printed
![Screenshot 2024-07-02 091050](https://github.com/tom-writes-code/rpgle-repl/assets/56802156/6d76d13a-9d64-4d86-bda4-b3950c106d70)

**Comment by tom-writes-code** [comment]
I will double check this as well, but I think you're missing a closing brace on the replEquals lines at the end - and I did notice as I was putting it in that we end up not printing this as an error. I'm still thinking on the best way of representing this.

That _might_ help, but I do also suspect that I'm not always going to parse a suitable response from procedures. I have been experimenting with overloaded procedures though, so we should be getting closer.

**Comment by tom-writes-code** [comment]
Ah, yes, this looks like it'll be fixed when I do the next release, which will hopefully be in the next few hours
![image](https://github.com/user-attachments/assets/4fd96afd-0c96-4441-a3d0-6c9b67517206)
