### ISSUE TITLE
2.4.1 release no Save file attached

### ISSUE THREAD

**Issue by priceaj** [tom-writes-code/rpgle-repl#57]
FYI there isn't an RPGLEREPL.FILE attached to the release for the 2.4.1 release

https://github.com/tom-writes-code/rpgle-repl/releases/latest/download/RPGLEREPL.FILE gives a 404

**Comment by tom-writes-code** [comment]
Woops, that's what I get for building releases late on a Friday night, not seeing the "failed to upload" notice.

I've uploaded that now.
