### ISSUE TITLE
Wiki upgrade instructions cannot run command

### ISSUE THREAD

**Issue by priceaj** [tom-writes-code/rpgle-repl#59]
https://github.com/tom-writes-code/rpgle-repl/wiki/Installation-and-Launch#upgrading-repl

Runinng:

`CPYF FROMFILE(OLDREPL/REPLSRC) TOFILE(RPGREPL/REPLSRC) FROMMBR(*ALL) TOMBR(*ALL) MBROPT(*REPLACE) FMTOPT(*MAP *DROP)      `

 I get message:       

Output only and MBR(*ALL) cannot be used together.                           + 

I believe the correct command is:

CPYF FROMFILE(OLDREPL/REPLSRC) TOFILE(RPGREPL/REPLSRC) FROMMBR(*ALL) TOMBR(*FROMMBR) MBROPT(*REPLACE) FMTOPT(*MAP *DROP)

**Comment by tom-writes-code** [comment]
Thanks! I've updated those instructions now. I'd like to go over the installation instructions as a whole, they're a bit all over the place, but just keeping them in line will do for now.
