### ISSUE TITLE
Convert from service programs to multi-module program

### ISSUE THREAD

**Issue by martintosney** [tom-writes-code/rpgle-repl#6]
Now that we're free from the confines of our previous change management system, multi-module programs are not as painful to develop.

I think the architecture could be improved by changing the binding so that most of the existing service programs are ditched, and we instead bind the module in directly to the program. REPL_HLPR would be the exception, since that's used in the generated program.

**Comment by martintosney** [comment]
After further research, I'm not sure how worthwhile this is actually is. Almost all the modules are shared between REPL and REPLLOAD, so that means building two programs every time a module is changed, versus one service program.

I'm just going to close this one, unless you have any bright ideas @tom-writes-code .

**Comment by tom-writes-code** [comment]
I didn't think REPLLOAD actually had that many dependencies, but I'm also happy to leave it for the time being - I like a structure I'm much more familiar with while I'm still getting used to the new change management system.

**Comment by martintosney** [comment]
Not directly, but once you bind all the transitive dependencies you end up bringing in half the project 😄 

I'll close this.
